// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"backend/internal/api/handler"
	"backend/internal/api/middleware"
	"backend/internal/api/router"
	"backend/internal/repository/category"
	"backend/internal/repository/favorites"
	"backend/internal/repository/prompt"
	"backend/internal/repository/recently_used"
	"backend/internal/repository/user"
	"backend/internal/repository/version"
	category2 "backend/internal/service/category"
	favorites2 "backend/internal/service/favorites"
	prompt2 "backend/internal/service/prompt"
	recently_used2 "backend/internal/service/recently_used"
	user2 "backend/internal/service/user"
	version2 "backend/internal/service/version"
	"backend/pkg/config"
	"go.uber.org/zap"
	"gopkg.in/natefinch/lumberjack.v2"
)

import (
	_ "github.com/go-sql-driver/mysql"
	_ "github.com/lib/pq"
	_ "github.com/mattn/go-sqlite3"
)

// Injectors from wire.go:

func wireApp(configConfig *config.Config, logger *lumberjack.Logger, zapLogger *zap.Logger) (*App, func(), error) {
	db, err := createDB(configConfig)
	if err != nil {
		return nil, nil, err
	}
	middlewareLogger := middleware.CreateLoggerMiddleware(zapLogger)
	recovery := middleware.CreateRecoveryMiddleware(logger)
	cors := middleware.CreateCORSMiddleware()
	jwtMiddleware := middleware.CreateJWTMiddleware(configConfig)
	repo := user.CreateRepo(db)
	service := user2.CreateUserService(repo)
	userHandler := handler.CreateUserHandler(service, configConfig)
	promptRepo := prompt.CreatePromptRepo(db)
	promptService := prompt2.CreatePromptService(promptRepo, zapLogger)
	versionRepo := version.CreateVersionRepo(db)
	versionService := version2.CreateVersionService(versionRepo, promptRepo, zapLogger)
	promptHandler := handler.CreatePromptHandler(promptService, versionService)
	promptVersionHandler := handler.CreatePromptVersionHandler(versionService)
	categoryRepo := category.CreateCategoryRepo(db)
	categoryService := category2.CreateCategoryService(categoryRepo, zapLogger)
	categoryHandler := handler.CreateCategoryHandler(categoryService)
	favoritesRepo := favorites.CreateFavoriteRepo(db)
	favoritesService := favorites2.CreateFavoriteService(favoritesRepo, zapLogger)
	favoriteHandler := handler.CreateFavoriteHandler(favoritesService)
	recently_usedRepo := recently_used.CreateRecentlyUsedRepo(db)
	recently_usedService := recently_used2.CreateRecentlyUsedService(recently_usedRepo, zapLogger)
	recentlyUsedHandler := handler.CreateRecentlyUsedHandler(recently_usedService)
	engine := router.SetupRouter(configConfig, middlewareLogger, recovery, cors, jwtMiddleware, userHandler, promptHandler, promptVersionHandler, categoryHandler, favoriteHandler, recentlyUsedHandler)
	server := createHttpServer(configConfig, engine)
	app, err := createApp(db, configConfig, zapLogger, server)
	if err != nil {
		return nil, nil, err
	}
	return app, func() {
	}, nil
}
